// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.src.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RestaurantAPI.src.Modal.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4521),
                            IsActive = true,
                            PasswordHash = "$2a$11$1Ig2wqnOdBpqBuT.BAfsJe0Lxrte/gpsXvm6docROLgjldges2FXe",
                            Role = "ADMIN",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4538),
                            IsActive = true,
                            PasswordHash = "$2a$11$Jntx8qUE/6yFwqJnIOk7kO1jvIFjb6.MVr8sYfgB9GL/kmClusZsC",
                            Role = "STAFF",
                            Username = "staff"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4539),
                            IsActive = true,
                            PasswordHash = "$2a$11$lLfoCr9.x.gW.I43R3lTxutgMu6T8qJVAaID088sPAY2YWIo3sH6K",
                            Role = "CUSTOMER",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Combo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("combos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Combo 2 người",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Combo gia đình",
                            Price = 350000m
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.ComboItem", b =>
                {
                    b.Property<long>("ComboId")
                        .HasColumnType("bigint")
                        .HasColumnName("combo_id");

                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("ComboId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("combo_items");

                    b.HasData(
                        new
                        {
                            ComboId = 1L,
                            MenuItemId = 1L,
                            Quantity = 1
                        },
                        new
                        {
                            ComboId = 1L,
                            MenuItemId = 3L,
                            Quantity = 2
                        },
                        new
                        {
                            ComboId = 2L,
                            MenuItemId = 1L,
                            Quantity = 2
                        },
                        new
                        {
                            ComboId = 2L,
                            MenuItemId = 2L,
                            Quantity = 1
                        },
                        new
                        {
                            ComboId = 2L,
                            MenuItemId = 3L,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 3L,
                            Email = "ntmh@sv.sgu.edu.vn",
                            FullName = "Nguyễn Thị Mỹ Hạnh",
                            Phone = "0346685730",
                            Points = 1200
                        },
                        new
                        {
                            Id = 2L,
                            Email = "tch@sv.ptit.edu.vn",
                            FullName = "Trần Công Hậu",
                            Phone = "01669127737",
                            Points = 80
                        },
                        new
                        {
                            Id = 3L,
                            Email = "ntp@sv.hub.edu.vn",
                            FullName = "Nguyễn Tiến Phát",
                            Phone = "0933681888",
                            Points = 200
                        },
                        new
                        {
                            Id = 4L,
                            Email = "ntn@sv.nttu.edu.vn",
                            FullName = "Nguyễn Trọng Nghĩa",
                            Phone = "0934567890",
                            Points = 50
                        },
                        new
                        {
                            Id = 5L,
                            Email = "nmt@sv.hcmurne.edu.vn",
                            FullName = "Nguyễn Minh Thiện",
                            Phone = "0945678901",
                            Points = 150
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.CustomerVoucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "DISCOUNT10",
                            CustomerId = 1L,
                            Discount = 10000m,
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false
                        },
                        new
                        {
                            Id = 2L,
                            Code = "VIP50",
                            CustomerId = 2L,
                            Discount = 50000m,
                            ExpiryDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Ingredients", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MinQuantity = 10m,
                            Name = "Gạo",
                            StockQuantity = 1000m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2L,
                            MinQuantity = 5m,
                            Name = "Thịt bò",
                            StockQuantity = 1000m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 3L,
                            MinQuantity = 5m,
                            Name = "Tôm",
                            StockQuantity = 1000m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 4L,
                            MinQuantity = 200m,
                            Name = "Trà",
                            StockQuantity = 1000m,
                            Unit = "g"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.InventoryLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_date");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_type");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("inventory_logs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IngredientId = 1L,
                            LogType = "IN",
                            Quantity = 50m
                        },
                        new
                        {
                            Id = 2L,
                            IngredientId = 2L,
                            LogType = "IN",
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 3L,
                            IngredientId = 3L,
                            LogType = "OUT",
                            Quantity = 5m
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("service_fee");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("vat");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("invoices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4817),
                            Discount = 0m,
                            OrderId = 2L,
                            ServiceFee = 5000m,
                            Subtotal = 120000m,
                            Total = 137000m,
                            Vat = 12000m
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.MenuCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("menu_categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Món chính"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("menu_items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Cơm chiên với tôm, mực",
                            Name = "Cơm chiên hải sản",
                            Price = 75000m,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Description = "Bò xào mềm",
                            Name = "Bò lúc lắc",
                            Price = 120000m,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2L,
                            Description = "Trà đào mát lạnh",
                            Name = "Trà đào",
                            Price = 30000m,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2L,
                            Description = "Cà phê truyền thống",
                            Name = "Cà phê sữa",
                            Price = 25000m,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 3L,
                            Description = "Tráng miệng",
                            Name = "Bánh flan",
                            Price = 20000m,
                            Status = "AVAILABLE"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.HasKey("Id");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 1L,
                            CustomerId = 1L,
                            OrderTime = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4736),
                            Status = "OPEN",
                            TableId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AccountId = 2L,
                            CustomerId = 2L,
                            OrderTime = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4738),
                            Status = "PAID",
                            TableId = 2L
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_item_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MenuItemId = 1L,
                            OrderId = 1L,
                            Price = 75000m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2L,
                            MenuItemId = 3L,
                            OrderId = 1L,
                            Price = 30000m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3L,
                            MenuItemId = 2L,
                            OrderId = 2L,
                            Price = 120000m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("payments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 137000m,
                            InvoiceId = 1L,
                            Method = "CASH",
                            PaymentTime = new DateTime(2026, 4, 10, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4837),
                            Status = "SUCCESS"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Recipe", b =>
                {
                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_item_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("quantity");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipes");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1L,
                            IngredientId = 1L,
                            Quantity = 5m
                        },
                        new
                        {
                            MenuItemId = 1L,
                            IngredientId = 3L,
                            Quantity = 5m
                        },
                        new
                        {
                            MenuItemId = 2L,
                            IngredientId = 2L,
                            Quantity = 5m
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int")
                        .HasColumnName("guest_count");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reservation_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("reservations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CustomerId = 1L,
                            GuestCount = 5,
                            ReservationTime = new DateTime(2026, 4, 11, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4926),
                            Status = "CONFIRMED",
                            TableId = 4L
                        },
                        new
                        {
                            Id = 2L,
                            CustomerId = 2L,
                            GuestCount = 2,
                            ReservationTime = new DateTime(2026, 4, 12, 10, 52, 47, 128, DateTimeKind.Local).AddTicks(4932),
                            Status = "PENDING",
                            TableId = 2L
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Table", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int")
                        .HasColumnName("seat_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("table_code");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            SeatCount = 4,
                            Status = "EMPTY",
                            TableCode = "T01"
                        },
                        new
                        {
                            Id = 2L,
                            SeatCount = 4,
                            Status = "EMPTY",
                            TableCode = "T02"
                        },
                        new
                        {
                            Id = 3L,
                            SeatCount = 6,
                            Status = "OCCUPIED",
                            TableCode = "VIP-01"
                        },
                        new
                        {
                            Id = 4L,
                            SeatCount = 10,
                            Status = "RESERVED",
                            TableCode = "VIP-02"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.ComboItem", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Combo", "Combo")
                        .WithMany("Items")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.src.Modal.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Customer", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.CustomerVoucher", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Customer", "Customer")
                        .WithMany("CustomerVouchers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.InventoryLogs", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Ingredients", "Ingredients")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Invoice", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.MenuItem", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.MenuCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.OrderItem", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.src.Modal.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Recipe", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Ingredients", "Ingredients")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.src.Modal.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredients");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Reservation", b =>
                {
                    b.HasOne("RestaurantAPI.src.Modal.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.src.Modal.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Combo", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Customer", b =>
                {
                    b.Navigation("CustomerVouchers");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Ingredients", b =>
                {
                    b.Navigation("InventoryLogs");
                });

            modelBuilder.Entity("RestaurantAPI.src.Modal.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
